FORMAT: 1A
HOST: http://test.onco-reg.ru

# API Протокол взаимодействия МИС Медофис и ЛИС ДокФлоу
Типы используемых данных:
- Целое число - строковое представление целого беззнакового в десятичной системе счисления
- Строка - строка в кодировке UTF-8
- Дата - дата/время представленное в соответствии ГОСТ ИСО 8601-2001

# Group Основные операции

<!-- include(patReferral/getList/index.md) -->

<!-- include(patReferral/setImported/index.md) -->

<!-- include(patReferral/setResult/index.md) -->

<!-- include(patReferral/help/index.md) -->
